pipeline {
    agent any

    stages {
        stage('GIT') {
            steps {
                echo "Getting Project from Git"
                script {
                    checkout([$class: 'GitSCM', branches: [[name: 'PFE']], userRemoteConfigs: [[url: 'https://github.com/Tasnimnaji/Intern.git']]])
                }
            }
        }


        stage('Execute Python Script') {
            steps {
                // Change directory to where your Python script is located
                dir('test1/src') {
                    // Execute the Python script using Python 3
                    sh 'python3 run1.py'
                }
            }
        }

        // Add more stages if needed
    }
}
